apiVersion: v1
kind: Service
metadata:
  name: addressbook
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.99.243
  ports:
  - name: addressbook
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: addressbook
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
